[package]
name = "lovm2_extend"
version = "0.1.0"
authors = ["lausek <root@lausek.eu>"]
edition = "2018"

[lib]
name = "lovm2_extend"

[dependencies]
libloading = "0.6.2"
lovm2 = { path = "../" }
lovm2_module = { path = "./lovm2_module/" }
