[package]
name = "shared-module"
version = "0.1.0"
authors = ["lausek <root@lausek.eu>"]
edition = "2018"

[workspace]

[lib]
name = "shared_module"
crate-type = ["cdylib"]

[dependencies]
lovm2_extend = { path = "../../crates/lovm2_extend" }