[package]
name = "lovm2"
version = "0.1.0"
authors = ["lausek <root@lausek.eu>"]
edition = "2018"

[[bin]]
name = "lovm2-repl"
path = "bin/bin.rs"

[lib]
name = "lovm2"
path = "src/lib.rs"

[dependencies]
lovm2_internals = { path = "src/lovm2_internals" }
