[package]
name = "lovm2"
version = "0.4.6"
authors = ["lausek <root@lausek.eu>"]
edition = "2018"

homepage = "https://github.com/lausek/lovm2"
repository = "https://github.com/lausek/lovm2"
readme = "README.md"
keywords = ["interpreter"]
license-file = "LICENSE"
description = "a lightweight virtual machine with a focus on simplicity and extendability."

[[bin]]
name = "lovm2-repl"
path = "bin/bin.rs"
bench = false

[lib]
name = "lovm2"
path = "src/lib.rs"
bench = false

[dependencies]
lovm2_error = { path = "./src/lovm2_error", version = "0.1.1" }
lovm2_internals = { path = "./src/lovm2_internals", version = "0.2.1" }
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3.1"
libloading = "0.6.5"
dirs = "3.0.1"

[dev-dependencies]
criterion = "0.3.3"

[[bench]]
name = "lovm2"
path = "bench/bin.rs"
harness = false
