[package]
name = "lovm2_std_json"
version = "0.1.0"
authors = ["lausek <root@lausek.eu>"]
edition = "2018"

[lib]
name = "lovm2_std_json"
crate-type = ["cdylib", "rlib"]

[dependencies]
json = "0.12.4"
lovm2 = { path = "../../" }
lovm2_extend = { path = "../../lovm2_extend" }
