[package]
name = "lovm2_std_regex"
version = "0.1.0"
authors = ["lausek <root@lausek.eu>"]
edition = "2018"

[lib]
name = "lovm2_std_regex"
crate-type = ["cdylib", "rlib"]

[dependencies]
lovm2 = { path = "../../" }
lovm2_extend = { path = "../../lovm2_extend" }
regex = "1.4.2"
