[package]
name = "custom-objects"
version = "0.1.0"
authors = ["lausek <root@lausek.eu>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
lovm2_extend = { path = "../../" }

[dev-dependencies]
lovm2 = { path = "../../../" }
