[package]
name = "lovm2_std"
version = "0.1.0"
authors = ["lausek <root@lausek.eu>"]
edition = "2018"

[lib]
path = "src/lib.rs"

#[workspace]
#members = [
#    "lovm2_std_collection",
#    "lovm2_std_string",
#]
