[package]
name = "lovm2_internals"
version = "0.2.0"
authors = ["lausek <root@lausek.eu>"]
edition = "2018"

[lib]
proc-macro = true
name = "lovm2_internals"
path = "src/lib.rs"

[dependencies]
quote = "1.0"

[dependencies.syn]
version = "1.0.33"
features = ["full"]
