[package]
name = "lovm2_std_string"
version = "0.1.0"
authors = ["lausek <root@lausek.eu>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
lovm2 = { path = "../../" }
lovm2_extend = { path = "../../lovm2_extend" }
