[package]
name = "static-module"
version = "0.1.0"
authors = ["lausek <root@lausek.eu>"]
edition = "2018"

[workspace]

[lib]
name = "static_module"

[dependencies]
lovm2_extend = { path = "../../crates/lovm2_extend" }