[package]
name = "lovm2_std_functional"
version = "0.1.0"
authors = ["witling <noreply@my.email>"]
edition = "2018"

[lib]
name = "lovm2_std_functional"
crate-type = ["cdylib", "rlib"]

[dependencies]
json = "0.12.4"
lovm2 = { path = "../../" }
lovm2_extend = { path = "../../lovm2_extend" }
