[package]
name = "so_module"
version = "0.1.0"
authors = ["lausek <root@lausek.eu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
lovm2_extend = { path = "../../lovm2_extend" }
