#[build-system]
#requires = ["setuptools", "wheel", "setuptools-rust"]

[build-system]
requires = ["maturin>=0.12,<0.13"]
build-backend = "maturin"

[tool.maturin]
#bindings = "cffi"
bindings = "pyo3"
#manylinux = "off"
