[package]
name = "pylovm2"
version = "0.1.0"
authors = ["lausek <root@lausek.eu>"]
edition = "2018"

[lib]
name = "pylovm2"
crate-type = ["cdylib"]

[dependencies]
shrinkwraprs = "0.3.0"
lovm2 = { version = "0.4.0" }

[dependencies.pyo3]
version = "0.12.3"
features = ["extension-module"]
